export const ADD_CART_PIZZA = "ADD_CART_PIZZA";
export const REMOVE_CART_PIZZA = "REMOVE_CART_PIZZA";
export const QUANTITY_CART_PIZZA = "QUANTITY_CART_PIZZA";
export const CLEAR_CART_PIZZA = "CART_RESET";
